/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 942b0a9e5b18a21a0e04db648eb0dce0)
interface __BaseEnv_Env {
	REPORTS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	BUILDER_URL: "http://127.0.0.1:8788";
	GITHUB_API: "https://api.github.com";
	GITHUB_OAUTH: "https://github.com";
	GITHUB_APP_ID: "";
	GITHUB_APP_CLIENT_ID: "";
	GITHUB_APP_SLUG: "";
	BUILDER_SECRET: string;
	GITHUB_TOKEN: string;
	GITHUB_APP_CLIENT_SECRET: string;
	GITHUB_APP_PRIVATE_KEY: string;
	GITHUB_WEBHOOK_SECRET: string;
	SESSION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BUILDER_URL" | "GITHUB_API" | "GITHUB_OAUTH" | "GITHUB_APP_ID" | "GITHUB_APP_CLIENT_ID" | "GITHUB_APP_SLUG" | "BUILDER_SECRET" | "GITHUB_TOKEN" | "GITHUB_APP_CLIENT_SECRET" | "GITHUB_APP_PRIVATE_KEY" | "GITHUB_WEBHOOK_SECRET" | "SESSION_KEY">> {}
}
