//! Which files at HEAD a person wrote, and which no person should be asked to
//! look at.
//!
//! A hotspot list headed by `pnpm-lock.yaml` makes the tool look broken on
//! first run, so every Generated File is excluded from every ranking. The
//! repository's own declarations come first: `.gitattributes` with
//! `linguist-generated` or `linguist-vendored`, the attributes GitHub reads,
//! set or explicitly unset. After that, conventions that are close to
//! certain: lockfile names, ORM snapshots, `*.gen.*` and similar outputs,
//! minified bundles, snapshot tests, a generator's header comment, and the
//! directory names package managers vendor into.

use commitscape_core::FileClass;
use globset::{Glob, GlobBuilder, GlobSet, GlobSetBuilder};

/// Bumped whenever a rule here changes. A cache classified by another version
/// has its HEAD table classified again; its history is kept.
pub const CLASSIFIER_VERSION: u32 = 5;

/// Files that a package manager or build tool writes.
const LOCKFILES: &[&str] = &[
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "bun.lockb",
    "deno.lock",
    "Cargo.lock",
    "Gemfile.lock",
    "composer.lock",
    "poetry.lock",
    "Pipfile.lock",
    "uv.lock",
    "pdm.lock",
    "pixi.lock",
    "go.sum",
    "go.work.sum",
    "flake.lock",
    "mix.lock",
    "pubspec.lock",
    "Podfile.lock",
    "Package.resolved",
    "packages.lock.json",
    "gradle.lockfile",
    "conan.lock",
    "Cartfile.resolved",
    ".terraform.lock.hcl",
    "shard.lock",
    "cabal.project.freeze",
    "stack.yaml.lock",
    "MODULE.bazel.lock",
    ".pnp.cjs",
    ".pnp.loader.mjs",
];

/// File name endings that only generators produce.
const GENERATED_SUFFIXES: &[&str] = &[
    ".min.js",
    ".min.mjs",
    ".min.css",
    ".js.map",
    ".mjs.map",
    ".css.map",
    ".d.ts.map",
    ".pb.go",
    ".pb.cc",
    ".pb.h",
    "_pb2.py",
    "_pb2_grpc.py",
    "_pb2.pyi",
    ".pb.dart",
    ".pbjson.dart",
    "_pb.js",
    "_pb.d.ts",
    "_grpc_pb.js",
    ".g.dart",
    ".freezed.dart",
    ".designer.cs",
    ".Designer.cs",
    ".snap",
];

/// Fragments of a file name that mark generator output: `routeTree.gen.ts`,
/// `schema.generated.ts`, `zz_generated.deepcopy.go`.
const GENERATED_INFIXES: &[&str] = &[".gen.", ".generated.", "_generated.", "zz_generated"];

/// Directories an IDE writes its project files into: JetBrains keeps
/// `.idea/`, Xcode `App.xcodeproj/` and `App.xcworkspace/`. People commit
/// them; nobody writes them.
fn is_ide_project(path: &str) -> bool {
    path.split('/').rev().skip(1).any(|segment| {
        segment == ".idea" || segment.ends_with(".xcodeproj") || segment.ends_with(".xcworkspace")
    })
}

/// Path segments package managers and vendoring tools write into.
const VENDOR_DIRS: &[&str] = &[
    "vendor",
    "vendors",
    "node_modules",
    "bower_components",
    "jspm_packages",
    "third_party",
    "third-party",
    "thirdparty",
    "Pods",
    "Carthage",
];

/// Phrases a generator writes into the top of its output, compared in lower
/// case against the first kilobyte.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "code generated",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "this file is generated",
    "this file was generated",
];

/// Extensions of files written to be read rather than run.
const PROSE_EXTENSIONS: &[&str] = &[
    ".md",
    ".markdown",
    ".rst",
    ".adoc",
    ".asciidoc",
    ".txt",
    ".org",
    ".textile",
];

/// Documents conventionally named without an extension.
const PROSE_NAMES: &[&str] = &[
    "README",
    "CHANGELOG",
    "CHANGES",
    "NEWS",
    "AUTHORS",
    "CONTRIBUTORS",
    "CREDITS",
    "MAINTAINERS",
    "INSTALL",
    "HACKING",
    "THANKS",
    "TODO",
    "COPYING",
    "LICENSE",
    "LICENCE",
    "NOTICE",
];

/// How much of a file's start is searched for a generator's marker.
const HEADER_BYTES: usize = 1024;

/// Average line length above which a script or stylesheet is minified.
const MINIFIED_LINE_LENGTH: usize = 300;

/// More lines than anyone writes by hand. Files this long are dumps,
/// amalgamations, rendered output or data: rust-lang/rust has a 313,000-line
/// HTML example, Linux has register tables of 100,000 to 220,000 lines.
const MACHINE_SIZED_LINES: usize = 100_000;

/// A C or C++ header this long that is nearly all `#define` lines is a
/// generated constant table, such as a hardware register map.
const DEFINE_TABLE_MIN_LINES: usize = 1_000;
const DEFINE_TABLE_SHARE: f64 = 0.9;

/// The value one `.gitattributes` line gives a linguist attribute.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Setting {
    Set,
    Unset,
    /// `!attr`: back to unspecified.
    Reset,
}

#[derive(Debug, Clone, Copy)]
struct Rule {
    generated: Option<Setting>,
    vendored: Option<Setting>,
    binary: bool,
}

/// Classifies files, given the `.gitattributes` files at HEAD.
pub struct Classifier {
    globs: GlobSet,
    /// Parallel to the globs, in precedence order: later entries win.
    rules: Vec<Rule>,
    /// Directories that are other projects' checkouts, each ending in `/`.
    nested_projects: Vec<Vec<u8>>,
}

impl Classifier {
    /// `gitattributes` pairs each file's directory, as a path prefix ending in
    /// `/` or empty for the root, with its contents. Shallower files must come
    /// first: a deeper `.gitattributes` overrides a shallower one.
    ///
    /// Everything under `nested_projects` is vendored unless declared
    /// otherwise; see [`nested_projects`].
    pub fn new(gitattributes: &[(Vec<u8>, Vec<u8>)], nested_projects: Vec<Vec<u8>>) -> Classifier {
        let mut builder = GlobSetBuilder::new();
        let mut rules = Vec::new();
        for (dir, contents) in gitattributes {
            let dir = String::from_utf8_lossy(dir);
            for line in String::from_utf8_lossy(contents).lines() {
                let Some((glob, rule)) = parse_line(&dir, line) else {
                    continue;
                };
                builder.add(glob);
                rules.push(rule);
            }
        }
        let globs = builder.build().unwrap_or_else(|_| GlobSet::empty());
        Classifier {
            globs,
            rules,
            nested_projects,
        }
    }

    /// Classifies one file at HEAD from its path and contents.
    pub fn classify(&self, path: &[u8], contents: &[u8], symlink: bool) -> FileClass {
        if symlink {
            return FileClass::Symlink;
        }
        let path = String::from_utf8_lossy(path);
        let declared = self.declared(&path);
        if declared.binary || looks_binary(contents) {
            return FileClass::Binary;
        }
        let nested = self
            .nested_projects
            .iter()
            .any(|dir| path.as_bytes().starts_with(dir));
        match declared.vendored {
            Some(Setting::Set) => return FileClass::Vendored,
            Some(Setting::Unset) => {}
            _ if nested || is_vendored_path(&path) => return FileClass::Vendored,
            _ => {}
        }
        // A lockfile is machine-written whatever `.gitattributes` says.
        // rust-lang/rust sets `Cargo.lock linguist-generated=false`, which
        // makes GitHub show its diffs; it does not make a person its author.
        if LOCKFILES.contains(&file_name(&path)) {
            return FileClass::Generated;
        }
        let generated = match declared.generated {
            Some(Setting::Set) => true,
            Some(Setting::Unset) => false,
            _ => is_generated(&path, contents),
        };
        if generated {
            FileClass::Generated
        } else if is_prose(file_name(&path)) {
            FileClass::Prose
        } else {
            FileClass::Source
        }
    }

    /// The attributes `.gitattributes` gives a path, last match winning.
    fn declared(&self, path: &str) -> Rule {
        let mut out = Rule {
            generated: None,
            vendored: None,
            binary: false,
        };
        let mut matched = self.globs.matches(path);
        matched.sort_unstable();
        for i in matched {
            let Some(rule) = self.rules.get(i) else {
                continue;
            };
            if let Some(s) = rule.generated {
                out.generated = (s != Setting::Reset).then_some(s);
            }
            if let Some(s) = rule.vendored {
                out.vendored = (s != Setting::Reset).then_some(s);
            }
            out.binary |= rule.binary;
        }
        out
    }
}

/// One `.gitattributes` line, if it says anything about the attributes this
/// cares about.
fn parse_line(dir: &str, line: &str) -> Option<(Glob, Rule)> {
    let line = line.trim();
    if line.is_empty() || line.starts_with('#') {
        return None;
    }
    let mut parts = line.split_whitespace();
    let pattern = parts.next()?;
    // Negative patterns are not allowed in attributes files, and a pattern
    // naming a directory does not match the files inside it.
    if pattern.starts_with('!') || pattern.ends_with('/') {
        return None;
    }
    let mut rule = Rule {
        generated: None,
        vendored: None,
        binary: false,
    };
    for attr in parts {
        let (setting, name) = if let Some(n) = attr.strip_prefix('-') {
            (Setting::Unset, n)
        } else if let Some(n) = attr.strip_prefix('!') {
            (Setting::Reset, n)
        } else {
            match attr.split_once('=') {
                Some((n, "false")) => (Setting::Unset, n),
                Some((n, _)) => (Setting::Set, n),
                None => (Setting::Set, attr),
            }
        };
        match name {
            "linguist-generated" => rule.generated = Some(setting),
            "linguist-vendored" => rule.vendored = Some(setting),
            "binary" if setting == Setting::Set => rule.binary = true,
            _ => {}
        }
    }
    if rule.generated.is_none() && rule.vendored.is_none() && !rule.binary {
        return None;
    }
    // A pattern with a slash is relative to the attributes file's directory;
    // one without matches a file name at any depth below it.
    let pattern = pattern.strip_prefix('/').map_or_else(
        || {
            if pattern.contains('/') {
                format!("{dir}{pattern}")
            } else {
                format!("{dir}**/{pattern}")
            }
        },
        |anchored| format!("{dir}{anchored}"),
    );
    let glob = GlobBuilder::new(&pattern)
        .literal_separator(true)
        .build()
        .ok()?;
    Some((glob, rule))
}

/// Whether a change to `path` can change how *other* files are classified,
/// so every class has to be decided again. Any change to a `.gitattributes`
/// does. A lockfile, a license file or a nested `.github/` folder's file
/// appearing or disappearing can make or unmake a nested project; editing
/// one in place, which happens in most commits that add a dependency,
/// cannot.
pub fn is_classification_input(path: &[u8], added_or_deleted: bool) -> bool {
    let name = path.rsplit(|&b| b == b'/').next().unwrap_or(path);
    let name = String::from_utf8_lossy(name);
    let upper = name.to_ascii_uppercase();
    name == ".gitattributes"
        || (added_or_deleted
            && (LOCKFILES.contains(&name.as_ref())
                || ["LICENSE", "LICENCE", "COPYING"]
                    .iter()
                    .any(|l| upper.starts_with(l))
                || github_home(path).is_some()))
}

/// The directory a nested `.github/` folder sits in, ending in `/`, for a
/// path inside one: `vendor/x/` for `vendor/x/.github/ci.yml`. `None` at
/// the root, where `.github/` is this repository's own.
fn github_home(path: &[u8]) -> Option<&[u8]> {
    const MARK: &[u8] = b"/.github/";
    let at = path.windows(MARK.len()).position(|w| w == MARK)?;
    path.get(..=at)
}

/// Directories below the root holding a lockfile and either a license file
/// or a `.github/` folder: another project's checkout, committed whole. A
/// monorepo's own packages share the root's lockfile; a project with its
/// own lockfile and its own license, or the `.github/` GitHub only reads at
/// a repository's root, was brought in from elsewhere. Each result ends in
/// `/`.
pub fn nested_projects<'p>(paths: impl Iterator<Item = &'p [u8]>) -> Vec<Vec<u8>> {
    let mut lockfile_dirs = std::collections::BTreeSet::new();
    let mut own_dirs = std::collections::BTreeSet::new();
    for path in paths {
        let Some(slash) = path.iter().rposition(|&b| b == b'/') else {
            continue;
        };
        let (dir, name) = path.split_at(slash + 1);
        let name = String::from_utf8_lossy(name);
        if LOCKFILES.contains(&name.as_ref()) {
            lockfile_dirs.insert(dir.to_vec());
        }
        let upper = name.to_ascii_uppercase();
        if ["LICENSE", "LICENCE", "COPYING"]
            .iter()
            .any(|l| upper.starts_with(l))
        {
            own_dirs.insert(dir.to_vec());
        }
        if let Some(home) = github_home(path) {
            own_dirs.insert(home.to_vec());
        }
    }
    let mut found: Vec<Vec<u8>> = lockfile_dirs.intersection(&own_dirs).cloned().collect();
    // A project nested inside another nested project is already covered.
    found.sort();
    let mut out: Vec<Vec<u8>> = Vec::new();
    for dir in found {
        if !out.iter().any(|outer| dir.starts_with(outer)) {
            out.push(dir);
        }
    }
    out
}

/// git's own test: a NUL byte in the first 8000 bytes.
fn looks_binary(contents: &[u8]) -> bool {
    contents.iter().take(8000).any(|&b| b == 0)
}

fn file_name(path: &str) -> &str {
    path.rsplit('/').next().unwrap_or(path)
}

fn is_vendored_path(path: &str) -> bool {
    let mut segments: Vec<&str> = path.split('/').collect();
    segments.pop();
    segments.iter().any(|s| VENDOR_DIRS.contains(s))
        || path.starts_with(".yarn/releases/")
        || path.starts_with(".yarn/plugins/")
}

fn is_generated(path: &str, contents: &[u8]) -> bool {
    let name = file_name(path);
    let stem = name.split('.').next().unwrap_or(name);
    if LOCKFILES.contains(&name)
        || (stem.eq_ignore_ascii_case("generated") && name.contains('.'))
        || GENERATED_SUFFIXES.iter().any(|s| name.ends_with(s))
        || GENERATED_INFIXES.iter().any(|s| name.contains(s))
        || is_orm_snapshot(path, name)
        || path.contains("__snapshots__/")
        || is_ide_project(path)
    {
        return true;
    }
    has_generator_marker(contents)
        || is_minified(name, contents)
        || is_define_table(name, contents)
        || line_count(contents) > MACHINE_SIZED_LINES
}

fn is_prose(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    PROSE_EXTENSIONS.iter().any(|ext| lower.ends_with(ext)) || PROSE_NAMES.contains(&name)
}

fn line_count(contents: &[u8]) -> usize {
    contents.iter().filter(|&&b| b == b'\n').count()
}

fn is_define_table(name: &str, contents: &[u8]) -> bool {
    let header = [".h", ".hh", ".hpp", ".hxx"]
        .iter()
        .any(|ext| name.ends_with(ext));
    if !header {
        return false;
    }
    let mut lines = 0usize;
    let mut defines = 0usize;
    for line in contents.split(|&b| b == b'\n') {
        let trimmed = line.trim_ascii_start();
        // Register maps label each register with a comment line; only code
        // lines count towards the share.
        let comment = [b"//".as_slice(), b"/*", b"*"]
            .iter()
            .any(|c| trimmed.starts_with(c));
        if trimmed.is_empty() || comment {
            continue;
        }
        lines += 1;
        if trimmed.starts_with(b"#define") {
            defines += 1;
        }
    }
    lines >= DEFINE_TABLE_MIN_LINES && defines as f64 >= DEFINE_TABLE_SHARE * lines as f64
}

/// Drizzle writes `meta/NNNN_snapshot.json` and `meta/_journal.json` beside
/// its migrations; newer versions write `<migration>/snapshot.json`.
fn is_orm_snapshot(path: &str, name: &str) -> bool {
    let in_meta = path.contains("/meta/") || path.starts_with("meta/");
    (in_meta && (name.ends_with("_snapshot.json") || name == "_journal.json"))
        || (name == "snapshot.json" && (path.contains("drizzle/") || path.contains("migrations/")))
}

fn has_generator_marker(contents: &[u8]) -> bool {
    let head = contents.get(..HEADER_BYTES).unwrap_or(contents);
    let head = String::from_utf8_lossy(head).to_lowercase();
    GENERATED_MARKERS.iter().any(|m| head.contains(m))
}

fn is_minified(name: &str, contents: &[u8]) -> bool {
    let script = [".js", ".mjs", ".cjs", ".css"]
        .iter()
        .any(|ext| name.ends_with(ext));
    if !script || contents.is_empty() {
        return false;
    }
    let lines = contents.iter().filter(|&&b| b == b'\n').count().max(1);
    contents.len() / lines > MINIFIED_LINE_LENGTH
}

#[cfg(test)]
mod tests {
    use super::*;

    fn plain() -> Classifier {
        Classifier::new(&[], Vec::new())
    }

    fn class(c: &Classifier, path: &str, contents: &str) -> FileClass {
        c.classify(path.as_bytes(), contents.as_bytes(), false)
    }

    #[test]
    fn lockfiles_are_generated_wherever_they_are() {
        let c = plain();
        for path in [
            "pnpm-lock.yaml",
            "package-lock.json",
            "yarn.lock",
            "Cargo.lock",
            "apps/web/bun.lock",
            "go.sum",
        ] {
            assert_eq!(
                class(&c, path, "anything\n"),
                FileClass::Generated,
                "{path}"
            );
        }
    }

    #[test]
    fn drizzle_snapshots_and_journals_are_generated() {
        let c = plain();
        for path in [
            "packages/database/drizzle/meta/0003_snapshot.json",
            "packages/database/drizzle/meta/_journal.json",
            "drizzle/20260101_init/snapshot.json",
        ] {
            assert_eq!(class(&c, path, "{}\n"), FileClass::Generated, "{path}");
        }
        assert_eq!(
            class(
                &c,
                "packages/database/drizzle/0003_add_users.sql",
                "create table x;\n"
            ),
            FileClass::Source,
            "the migration itself is reviewed and kept as source"
        );
    }

    #[test]
    fn generator_output_is_recognised_by_name() {
        let c = plain();
        for path in [
            "apps/dashboard/src/routeTree.gen.ts",
            "api/schema.generated.ts",
            "pkg/apis/zz_generated.deepcopy.go",
            "proto/user.pb.go",
            "dist/app.min.js",
            "src/__snapshots__/button.test.ts.snap",
        ] {
            assert_eq!(class(&c, path, "x\n"), FileClass::Generated, "{path}");
        }
    }

    #[test]
    fn project_files_an_ide_writes_are_generated() {
        let c = plain();
        for path in [
            ".idea/workspace.xml",
            ".idea/codeStyles/Project.xml",
            "apps/api/.idea/modules.xml",
            "ios/App.xcodeproj/project.pbxproj",
            "ios/App.xcworkspace/contents.xcworkspacedata",
        ] {
            assert_eq!(class(&c, path, "<xml/>\n"), FileClass::Generated, "{path}");
        }
        assert_eq!(
            class(&c, ".vscode/settings.json", "{}\n"),
            FileClass::Source,
            "people write these on purpose"
        );
    }

    #[test]
    fn a_generator_header_marks_a_file_generated() {
        let c = plain();
        let go = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage user\n";
        assert_eq!(class(&c, "api/user.go", go), FileClass::Generated);
        let ts =
            "/* eslint-disable */\n// This file was automatically generated by TanStack Router.\n";
        assert_eq!(class(&c, "src/routes.ts", ts), FileClass::Generated);
    }

    #[test]
    fn a_marker_deep_inside_a_file_is_not_a_header() {
        let c = plain();
        let mut body = "fn main() {}\n".repeat(200);
        body.push_str("// do not edit below this line\n");
        assert_eq!(class(&c, "src/main.rs", &body), FileClass::Source);
    }

    #[test]
    fn a_minified_script_is_generated_but_long_prose_is_not() {
        let c = plain();
        let bundle = format!("{}\n", "a=1;".repeat(400));
        assert_eq!(class(&c, "static/bundle.js", &bundle), FileClass::Generated);
        let prose = format!("{}\n", "word ".repeat(400));
        assert_eq!(
            class(&c, "docs/essay.md", &prose),
            FileClass::Prose,
            "long lines of prose are not a minified bundle"
        );
    }

    #[test]
    fn vendored_trees_are_vendored() {
        let c = plain();
        for path in [
            "vendor/github.com/pkg/errors/errors.go",
            "web/node_modules/left-pad/index.js",
            "third_party/zlib/inflate.c",
            ".yarn/releases/yarn-4.1.0.cjs",
        ] {
            assert_eq!(class(&c, path, "x\n"), FileClass::Vendored, "{path}");
        }
        assert_eq!(
            class(&c, "src/vendor.rs", "x\n"),
            FileClass::Source,
            "a file named vendor is not a vendored tree"
        );
    }

    #[test]
    fn binary_content_is_binary() {
        let c = plain();
        assert_eq!(
            c.classify(b"assets/logo.png", b"\x89PNG\r\n\x1a\n\0\0\0", false),
            FileClass::Binary
        );
    }

    #[test]
    fn a_symlink_is_a_symlink() {
        assert_eq!(
            plain().classify(b"docs/latest", b"v2", true),
            FileClass::Symlink
        );
    }

    #[test]
    fn gitattributes_declarations_win_over_conventions() {
        let root = (
            Vec::new(),
            b"docs/api/** linguist-generated\n\
              src/routes.gen.ts -linguist-generated\n\
              Cargo.lock linguist-generated=false\n\
              extern/** linguist-vendored\n\
              vendor/** linguist-vendored=false\n"
                .to_vec(),
        );
        let c = Classifier::new(&[root], Vec::new());
        assert_eq!(class(&c, "docs/api/index.md", "x\n"), FileClass::Generated);
        assert_eq!(
            class(&c, "src/routes.gen.ts", "x\n"),
            FileClass::Source,
            "explicitly unset: the owners say a person maintains it"
        );
        assert_eq!(
            class(&c, "Cargo.lock", "version = 3\n"),
            FileClass::Generated,
            "unsetting only makes GitHub show a lockfile's diffs"
        );
        assert_eq!(class(&c, "extern/lib/a.c", "x\n"), FileClass::Vendored);
        assert_eq!(
            class(&c, "vendor/ours/a.go", "x\n"),
            FileClass::Source,
            "explicitly not vendored"
        );
    }

    #[test]
    fn a_header_of_nothing_but_defines_is_a_generated_table() {
        let c = plain();
        // Linux's AMD register maps: a comment naming each register, then
        // its defines.
        let mut table = String::from("/* register map */\n#ifndef X\n");
        for i in 0..1200 {
            table.push_str(&format!("//REG_{i}\n#define REG_{i}__SHIFT 0x0\n"));
        }
        table.push_str("#endif\n");
        assert_eq!(
            class(&c, "include/asic_reg/x_sh_mask.h", &table),
            FileClass::Generated
        );

        let mut code = String::new();
        for i in 0..1200 {
            code.push_str(&format!("#define A{i} {i}\nint f{i}(void);\n"));
        }
        assert_eq!(
            class(&c, "include/api.h", &code),
            FileClass::Source,
            "half defines is a header a person maintains"
        );
    }

    #[test]
    fn a_file_longer_than_anyone_writes_by_hand_is_generated() {
        let c = plain();
        let huge = "<p>x</p>\n".repeat(100_001);
        assert_eq!(class(&c, "docs/example.html", &huge), FileClass::Generated);
        let long = "fn f() {}\n".repeat(20_000);
        assert_eq!(class(&c, "src/big.rs", &long), FileClass::Source);
    }

    #[test]
    fn documentation_is_prose() {
        let c = plain();
        for path in [
            "README.md",
            "docs/guide.rst",
            "RELEASES.md",
            "notes/todo.txt",
        ] {
            assert_eq!(class(&c, path, "# Title\n"), FileClass::Prose, "{path}");
        }
        assert_eq!(
            class(
                &c,
                "CHANGELOG.md",
                "<!-- This file is automatically generated -->\n"
            ),
            FileClass::Generated,
            "a generated changelog is generated first"
        );
    }

    #[test]
    fn a_file_named_generated_is_generated() {
        let c = plain();
        assert_eq!(
            class(&c, "packages/ai/openai/src/Generated.ts", "x\n"),
            FileClass::Generated
        );
        assert_eq!(
            class(&c, "src/generator.rs", "x\n"),
            FileClass::Source,
            "the tool that generates is not generated"
        );
    }

    #[test]
    fn another_projects_checkout_is_vendored() {
        let paths: Vec<&[u8]> = vec![
            b"LICENSE",
            b"pnpm-lock.yaml",
            b"src/app.ts",
            b".repos/effect/LICENSE",
            b".repos/effect/pnpm-lock.yaml",
            b".repos/effect/packages/effect/src/Effect.ts",
            b".repos/effect/examples/demo/LICENSE",
            b".repos/effect/examples/demo/yarn.lock",
            b"packages/ui/LICENSE",
            b"packages/ui/src/button.tsx",
        ];
        let projects = nested_projects(paths.into_iter());
        assert_eq!(
            projects,
            vec![b".repos/effect/".to_vec()],
            "the root is this project, and a package without its own lockfile is ours"
        );
        let c = Classifier::new(&[], projects.clone());
        assert_eq!(
            class(&c, ".repos/effect/packages/effect/src/Effect.ts", "x\n"),
            FileClass::Vendored
        );
        assert_eq!(
            class(&c, "packages/ui/src/button.tsx", "x\n"),
            FileClass::Source
        );

        let declared = Classifier::new(
            &[(Vec::new(), b".repos/** linguist-vendored=false\n".to_vec())],
            projects,
        );
        assert_eq!(
            class(
                &declared,
                ".repos/effect/packages/effect/src/Effect.ts",
                "x\n"
            ),
            FileClass::Source,
            "the repository's own declaration wins"
        );
    }

    #[test]
    fn a_checkout_with_its_own_github_folder_is_vendored_without_a_license() {
        // t3code keeps a copy of alchemy-effect under .repos/ with its own
        // bun.lock and .github/ but no license. GitHub reads .github/ only at
        // a repository's root, so one further down came with a copied
        // repository. A package with a .github/ but no lockfile of its own
        // is still this project's.
        let paths: Vec<&[u8]> = vec![
            b"bun.lock",
            b".github/workflows/ci.yml",
            b".repos/alchemy/bun.lock",
            b".repos/alchemy/.github/workflows/ci.yml",
            b".repos/alchemy/src/index.ts",
            b"packages/ui/.github/CODEOWNERS",
            b"packages/ui/src/button.tsx",
        ];
        assert_eq!(
            nested_projects(paths.into_iter()),
            vec![b".repos/alchemy/".to_vec()]
        );

        // Adding or removing such a folder's files can make or unmake a
        // nested project; the root's own .github/ cannot.
        assert!(is_classification_input(
            b".repos/alchemy/.github/workflows/ci.yml",
            true
        ));
        assert!(!is_classification_input(
            b".repos/alchemy/.github/workflows/ci.yml",
            false
        ));
        assert!(!is_classification_input(b".github/workflows/ci.yml", true));
    }

    #[test]
    fn a_nested_gitattributes_applies_below_its_directory_and_overrides() {
        let c = Classifier::new(
            &[
                (Vec::new(), b"*.json linguist-generated\n".to_vec()),
                (
                    b"config/".to_vec(),
                    b"*.json -linguist-generated\n".to_vec(),
                ),
            ],
            Vec::new(),
        );
        assert_eq!(class(&c, "data/x.json", "{}\n"), FileClass::Generated);
        assert_eq!(class(&c, "config/app.json", "{}\n"), FileClass::Source);
    }
}
